[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2024"
publish = false
license-file = "LICENSE.md"
repository = "https://github.com/swyrin/advent-of-code"
authors = ["Tien Dat Pham <hello@swyrin.me>"]

[workspace]
members = ["calendars/advent_2021", "calendars/advent_2024", "calendars/advent_2025", "crates/aoc_prelude", "crates/macros", "crates/macros_impl"]

[workspace.dependencies]
aoc_prelude = { path = "crates/aoc_prelude" }
macros = { path = "crates/macros" }
macros_impl = { path = "crates/macros_impl" }

[dependencies]
aoc_prelude.workspace = true
macros.workspace = true
macros_impl.workspace = true

[lints.cargo]
# https://github.com/rust-lang/cargo/issues/17449#issuecomment-5577945337
non_kebab_case_bins = "allow"
