[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2024"
publish = false
license-file = "LICENSE.md"
description = "Random BS go stuffs for Advent of Code."
repository = "https://github.com/swyrin/advent-of-code"
authors = [
    "Tien Dat Pham <hello@swyrin.me>"
]
default-run = "advent-of-code"

[dependencies]
anyhow = "1.0.104"
aoc-parse = "0.2.18"
counter = "0.7.1"
geo = "0.33.1"
good_lp = { version = "1.15.3", default-features = false, features = ["microlp"] }
image = { version = "0.25.10", default-features = false, features = ["png"] }
itertools = "0.15.0"
petgraph = { version = "0.8.3", features = ["rayon"] }
range-set-blaze = "0.6.0"

[dev-dependencies]
parameterized = "2.1.0"
