name: Test all of my AoC libs & submissions.

on:
  push:
  pull_request:

jobs:
  eyeball:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy
      - run: cargo fmt --check
      - run: cargo test
