name: Test all of my AoC libs & submissions.

on:
  push:
  pull_request:

jobs:
  eyeball:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy,rustfmt

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@nextest

      - run: cargo clippy

      - run: cargo fmt --check

      - run: cargo nextest run
